name: hornero
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - setuptools
  - setuptools_scm
  - click
  - distro
  - pyyaml
  - rich
  - pip:
      - pythondialog
  # Development
  - black
  - flake8
  - isort
  - pytest
